# Generated by Django 4.2.16 on 2025-11-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('failed', '失败')], db_index=True, default='running', max_length=20, verbose_name='状态')),
                ('file_path', models.CharField(blank=True, default='', max_length=500, verbose_name='备份文件路径')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='文件大小（字节）')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '备份任务',
                'verbose_name_plural': '备份任务',
                'db_table': 'backup_jobs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='如: 2024-01, 2024-Q1 等', max_length=50, verbose_name='统计周期')),
                ('exposure', models.IntegerField(default=0, help_text='内容的总曝光次数', verbose_name='曝光量')),
                ('likes', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comments', models.IntegerField(default=0, verbose_name='评论数')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='激励金额')),
                ('status', models.CharField(choices=[('applied', '已申请'), ('approved', '已批准'), ('rejected', '已拒绝'), ('granted', '已发放')], db_index=True, default='applied', max_length=20, verbose_name='状态')),
                ('review_note', models.TextField(blank=True, default='', verbose_name='审核备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='申请时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('granted_at', models.DateTimeField(blank=True, null=True, verbose_name='发放时间')),
            ],
            options={
                'verbose_name': '创作者激励',
                'verbose_name_plural': '创作者激励',
                'db_table': 'incentives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SysConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(help_text='可以是字符串或JSON格式', verbose_name='配置值')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='描述')),
                ('is_public', models.BooleanField(default=False, help_text='是否可以通过API公开访问', verbose_name='是否公开')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'sys_config',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SysLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', '调试'), ('INFO', '信息'), ('WARNING', '警告'), ('ERROR', '错误'), ('CRITICAL', '严重')], db_index=True, max_length=20, verbose_name='日志级别')),
                ('module', models.CharField(db_index=True, help_text='产生日志的模块名称', max_length=100, verbose_name='模块')),
                ('message', models.TextField(verbose_name='日志消息')),
                ('context', models.JSONField(blank=True, help_text='额外的上下文数据', null=True, verbose_name='上下文信息')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
                'db_table': 'sys_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
