# Generated by Django 4.2.16 on 2025-11-06 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='syslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sys_logs', to=settings.AUTH_USER_MODEL, verbose_name='相关用户'),
        ),
        migrations.AddField(
            model_name='incentive',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentives', to=settings.AUTH_USER_MODEL, verbose_name='创作者'),
        ),
        migrations.AddField(
            model_name='incentive',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_incentives', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddIndex(
            model_name='backupjob',
            index=models.Index(fields=['status', '-started_at'], name='backup_jobs_status_a59bea_idx'),
        ),
        migrations.AddIndex(
            model_name='syslog',
            index=models.Index(fields=['level', '-created_at'], name='sys_logs_level_d66798_idx'),
        ),
        migrations.AddIndex(
            model_name='syslog',
            index=models.Index(fields=['module', '-created_at'], name='sys_logs_module_54c6cd_idx'),
        ),
        migrations.AddIndex(
            model_name='syslog',
            index=models.Index(fields=['user', '-created_at'], name='sys_logs_user_id_83c89b_idx'),
        ),
        migrations.AddIndex(
            model_name='incentive',
            index=models.Index(fields=['author', '-created_at'], name='incentives_author__e9147d_idx'),
        ),
        migrations.AddIndex(
            model_name='incentive',
            index=models.Index(fields=['status', '-created_at'], name='incentives_status_5164ec_idx'),
        ),
        migrations.AddIndex(
            model_name='incentive',
            index=models.Index(fields=['period'], name='incentives_period_32246d_idx'),
        ),
    ]
