# Generated by Django 4.2.16 on 2025-11-06 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000, verbose_name='评论内容')),
                ('object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='反馈内容')),
                ('contact', models.CharField(blank=True, default='', max_length=200, verbose_name='联系方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='反馈时间')),
            ],
            options={
                'verbose_name': '反馈',
                'verbose_name_plural': '反馈',
                'db_table': 'feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000, verbose_name='内容')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('share_count', models.IntegerField(default=0, verbose_name='分享数')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '动态',
                'verbose_name_plural': '动态',
                'db_table': 'posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('like', '点赞'), ('dislike', '踩')], max_length=20, verbose_name='互动类型')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '互动',
                'verbose_name_plural': '互动',
                'db_table': 'reactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('content', models.TextField(help_text='举报原因说明', verbose_name='举报内容')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('resolved', '已处理')], db_index=True, default='pending', max_length=20, verbose_name='处理状态')),
                ('handle_result', models.TextField(blank=True, default='', verbose_name='处理结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='举报时间')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
            ],
            options={
                'verbose_name': '举报',
                'verbose_name_plural': '举报',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='话题名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='话题描述')),
                ('heat', models.FloatField(db_index=True, default=0.0, verbose_name='热度')),
                ('follow_count', models.IntegerField(default=0, verbose_name='关注数')),
                ('post_count', models.IntegerField(default=0, verbose_name='帖子数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '话题',
                'verbose_name_plural': '话题',
                'db_table': 'topics',
                'ordering': ['-heat', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='关注时间')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='community.topic', verbose_name='话题')),
            ],
            options={
                'verbose_name': '话题关注',
                'verbose_name_plural': '话题关注',
                'db_table': 'topic_follows',
                'ordering': ['-created_at'],
            },
        ),
    ]
