# Generated by Django 4.2.16 on 2025-11-06 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha', models.FloatField(default=0.7, help_text='总热度 = α * 静态热度 + β * 动态热度', verbose_name='静态热度权重 α')),
                ('beta', models.FloatField(default=0.3, help_text='总热度 = α * 静态热度 + β * 动态热度', verbose_name='动态热度权重 β')),
                ('decay_lambda', models.FloatField(default=0.05, help_text='衰减公式: exp(-λ * t)', verbose_name='时间衰减系数 λ')),
                ('weight_download', models.FloatField(default=0.5, verbose_name='下载权重')),
                ('weight_follow', models.FloatField(default=0.3, verbose_name='关注权重')),
                ('weight_review', models.FloatField(default=0.2, verbose_name='评价权重')),
                ('weight_like', models.FloatField(default=0.6, verbose_name='点赞权重')),
                ('weight_comment', models.FloatField(default=0.4, verbose_name='评论权重')),
                ('top_k', models.IntegerField(default=10, help_text='每个榜单/推荐列表返回的游戏数量', verbose_name='推荐数量 TopK')),
                ('refresh_hours', models.IntegerField(default=24, help_text='推荐列表的刷新间隔', verbose_name='刷新频率（小时）')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '算法配置',
                'verbose_name_plural': '算法配置',
                'db_table': 'algo_config',
            },
        ),
        migrations.CreateModel(
            name='GameMetricsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='日期')),
                ('downloads', models.IntegerField(default=0, verbose_name='下载数')),
                ('follows', models.IntegerField(default=0, verbose_name='关注数')),
                ('reviews', models.IntegerField(default=0, verbose_name='评价数')),
                ('posts', models.IntegerField(default=0, verbose_name='帖子数')),
                ('likes', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comments', models.IntegerField(default=0, verbose_name='评论数')),
                ('heat_static', models.FloatField(db_index=True, default=0.0, verbose_name='静态热度分')),
                ('heat_dynamic', models.FloatField(db_index=True, default=0.0, verbose_name='动态热度分')),
                ('heat_total', models.FloatField(db_index=True, default=0.0, verbose_name='总热度分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '游戏每日指标',
                'verbose_name_plural': '游戏每日指标',
                'db_table': 'game_metrics_daily',
                'ordering': ['-date', '-heat_total'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.JSONField(default=dict, help_text='存储推荐原因，如匹配的标签、相似度分数等', verbose_name='推荐理由')),
                ('score', models.FloatField(db_index=True, help_text='相似度或推荐强度分数', verbose_name='推荐分数')),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': '推荐记录',
                'verbose_name_plural': '推荐记录',
                'db_table': 'recommendations',
                'ordering': ['user', '-score', '-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0, help_text='用户对该标签的兴趣权重', verbose_name='权重')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_users', to='games.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '用户兴趣',
                'verbose_name_plural': '用户兴趣',
                'db_table': 'user_interests',
            },
        ),
    ]
