# Generated by Django 4.2.16 on 2025-11-06 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0002_initial'),
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='games.game', verbose_name='游戏'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='gamemetricsdaily',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='games.game', verbose_name='游戏'),
        ),
        migrations.AddIndex(
            model_name='userinterest',
            index=models.Index(fields=['user', '-weight'], name='user_intere_user_id_222a9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userinterest',
            unique_together={('user', 'tag')},
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['user', '-score'], name='recommendat_user_id_8236a6_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['game', '-generated_at'], name='recommendat_game_id_50465e_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['-generated_at'], name='recommendat_generat_387346_idx'),
        ),
        migrations.AddIndex(
            model_name='gamemetricsdaily',
            index=models.Index(fields=['game', '-date'], name='game_metric_game_id_c2d51f_idx'),
        ),
        migrations.AddIndex(
            model_name='gamemetricsdaily',
            index=models.Index(fields=['date', '-heat_total'], name='game_metric_date_8773fe_idx'),
        ),
        migrations.AddIndex(
            model_name='gamemetricsdaily',
            index=models.Index(fields=['-heat_total'], name='game_metric_heat_to_484f2f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gamemetricsdaily',
            unique_together={('game', 'date')},
        ),
    ]
