# Generated by Django 4.2.16 on 2025-11-06 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_hit_keywords', models.JSONField(blank=True, default=list, help_text='自动检测到的敏感词列表', verbose_name='自动命中关键词')),
                ('decision', models.CharField(choices=[('approved', '通过'), ('rejected', '拒绝')], max_length=20, verbose_name='审核决定')),
                ('reason', models.TextField(blank=True, help_text='拒绝时需要填写原因', null=True, verbose_name='审核原因')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='审核时间')),
            ],
            options={
                'verbose_name': '内容审核',
                'verbose_name_plural': '内容审核',
                'db_table': 'content_reviews',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', '图片'), ('video', '视频')], max_length=20, verbose_name='媒体类型')),
                ('url', models.FileField(max_length=500, upload_to='strategies/%Y/%m/%d/', verbose_name='文件')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='存储文件大小、分辨率、时长等信息', verbose_name='元数据')),
                ('order', models.IntegerField(default=0, help_text='在攻略中的显示顺序', verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '媒体资源',
                'verbose_name_plural': '媒体资源',
                'db_table': 'media_assets',
                'ordering': ['strategy', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='标题')),
                ('content', models.TextField(help_text='支持富文本', verbose_name='内容')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('collect_count', models.IntegerField(default=0, verbose_name='收藏数')),
                ('publish_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '攻略',
                'verbose_name_plural': '攻略',
                'db_table': 'strategies',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectors', to='content.strategy', verbose_name='攻略')),
            ],
            options={
                'verbose_name': '攻略收藏',
                'verbose_name_plural': '攻略收藏',
                'db_table': 'strategy_collections',
                'ordering': ['-created_at'],
            },
        ),
    ]
