# Generated by Django 4.2.16 on 2025-11-06 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='strategycollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_collections', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='games.game', verbose_name='关联游戏'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='content.strategy', verbose_name='关联攻略'),
        ),
        migrations.AddField(
            model_name='contentreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='contentreview',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='content.strategy', verbose_name='关联攻略'),
        ),
        migrations.AddIndex(
            model_name='strategycollection',
            index=models.Index(fields=['user', '-created_at'], name='strategy_co_user_id_6cf6a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='strategycollection',
            unique_together={('user', 'strategy')},
        ),
        migrations.AddIndex(
            model_name='strategy',
            index=models.Index(fields=['game', '-publish_date'], name='strategies_game_id_205630_idx'),
        ),
        migrations.AddIndex(
            model_name='strategy',
            index=models.Index(fields=['author', '-created_at'], name='strategies_author__f83dcd_idx'),
        ),
        migrations.AddIndex(
            model_name='strategy',
            index=models.Index(fields=['status'], name='strategies_status_de6fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='strategy',
            index=models.Index(fields=['-like_count'], name='strategies_like_co_b0a6fe_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['strategy', 'order'], name='media_asset_strateg_2e1708_idx'),
        ),
        migrations.AddIndex(
            model_name='contentreview',
            index=models.Index(fields=['strategy', '-reviewed_at'], name='content_rev_strateg_5cee15_idx'),
        ),
        migrations.AddIndex(
            model_name='contentreview',
            index=models.Index(fields=['reviewer', '-reviewed_at'], name='content_rev_reviewe_a85ccc_idx'),
        ),
    ]
