# Generated by Django 4.2.16 on 2025-11-21 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='点赞时间')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='content.strategy', verbose_name='攻略')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_strategies', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '攻略点赞',
                'verbose_name_plural': '攻略点赞',
                'db_table': 'strategy_likes',
                'indexes': [models.Index(fields=['user', '-created_at'], name='strategy_li_user_id_d9e9f8_idx'), models.Index(fields=['strategy', '-created_at'], name='strategy_li_strateg_a900b3_idx')],
                'unique_together': {('user', 'strategy')},
            },
        ),
    ]
