# Generated by Django 4.2.16 on 2025-11-22 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0003_strategylike'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyViewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='阅读时间')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='content.strategy', verbose_name='攻略')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategy_views', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '攻略阅读事件',
                'verbose_name_plural': '攻略阅读事件',
                'db_table': 'strategy_view_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['strategy', '-created_at'], name='strategy_vi_strateg_548ea6_idx')],
            },
        ),
    ]
