# Generated by Django 4.2.16 on 2025-11-22 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0004_strategyviewevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.CreateModel(
            name='StrategyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_comments', to='content.strategy', verbose_name='攻略')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_comments', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '攻略评论',
                'verbose_name_plural': '攻略评论',
                'db_table': 'strategy_comments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['strategy', '-created_at'], name='strategy_co_strateg_71d160_idx')],
            },
        ),
    ]
