# Generated by Django 4.2.16 on 2025-11-22 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0005_strategy_comment_count_strategycomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='例如 2025-11 表示月份周期', max_length=20, verbose_name='周期')),
                ('exposure', models.IntegerField(default=0, verbose_name='曝光')),
                ('likes', models.IntegerField(default=0, verbose_name='点赞')),
                ('comments', models.IntegerField(default=0, verbose_name='评论')),
                ('publish_count', models.IntegerField(default=0, verbose_name='发布数量')),
                ('status', models.CharField(choices=[('applied', '已申请'), ('approved', '已通过'), ('rejected', '已拒绝'), ('granted', '已发放')], default='applied', max_length=20, verbose_name='状态')),
                ('reason', models.TextField(blank=True, default='', verbose_name='备注/拒绝原因')),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='激励金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_incentives', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '创作者激励',
                'verbose_name_plural': '创作者激励',
                'db_table': 'creator_incentives',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['author', '-created_at'], name='creator_incentives_author_idx'), models.Index(fields=['period'], name='creator_incentives_period_idx')],
            },
        ),
    ]
