# Generated by Django 4.2.16 on 2025-11-06 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='发行商名称')),
                ('contact_info', models.CharField(blank=True, max_length=500, null=True, verbose_name='联系方式')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='publishers/%Y/%m/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, default='', verbose_name='简介')),
                ('website', models.URLField(blank=True, default='', max_length=500, verbose_name='官网')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '发行商',
                'verbose_name_plural': '发行商',
                'db_table': 'publishers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='标签名称')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='标签描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='游戏名称')),
                ('category', models.CharField(db_index=True, help_text='如：动作、冒险、角色扮演、策略等', max_length=100, verbose_name='游戏类别')),
                ('rating', models.FloatField(db_index=True, default=0.0, help_text='0-10分', verbose_name='评分')),
                ('download_count', models.IntegerField(db_index=True, default=0, verbose_name='下载数')),
                ('follow_count', models.IntegerField(db_index=True, default=0, verbose_name='关注数')),
                ('review_count', models.IntegerField(db_index=True, default=0, verbose_name='评价数')),
                ('release_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='发行日期')),
                ('online_time', models.DateField(blank=True, null=True, verbose_name='上线时间')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='版本号')),
                ('description', models.TextField(blank=True, default='', verbose_name='游戏描述')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='games/covers/%Y/%m/', verbose_name='封面图')),
                ('heat_static', models.FloatField(db_index=True, default=0.0, verbose_name='静态热度分')),
                ('heat_dynamic', models.FloatField(db_index=True, default=0.0, verbose_name='动态热度分')),
                ('heat_total', models.FloatField(db_index=True, default=0.0, verbose_name='总热度分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.publisher', verbose_name='发行商')),
                ('tags', models.ManyToManyField(blank=True, related_name='games', to='games.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '游戏',
                'verbose_name_plural': '游戏',
                'db_table': 'games',
                'ordering': ['-heat_total', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='收藏时间')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectors', to='games.game', verbose_name='游戏')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'collections',
                'ordering': ['-created_at'],
            },
        ),
    ]
