# Generated by Django 4.2.16 on 2025-11-06 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['category'], name='games_categor_3abc27_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-rating'], name='games_rating_22b28e_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-download_count'], name='games_downloa_86f943_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-heat_total'], name='games_heat_to_6b5426_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['publisher'], name='games_publish_6d05c5_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-release_date'], name='games_release_6edf26_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['user', '-created_at'], name='collections_user_id_d015b5_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['game', '-created_at'], name='collections_game_id_26c2d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('user', 'game')},
        ),
    ]
