# Generated by Django 4.2.16 on 2025-11-21 11:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gamescreenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinglePlayerRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, default='3dm', max_length=50, verbose_name='来源')),
                ('rank', models.PositiveIntegerField(db_index=True, verbose_name='排名')),
                ('name', models.CharField(max_length=200, verbose_name='游戏名称')),
                ('english_name', models.CharField(blank=True, default='', max_length=200, verbose_name='英文名称')),
                ('developer', models.CharField(blank=True, default='', max_length=200, verbose_name='开发商')),
                ('publisher_name', models.CharField(blank=True, default='', max_length=200, verbose_name='发行商')),
                ('genre', models.CharField(blank=True, default='', max_length=100, verbose_name='类型')),
                ('platforms', models.CharField(blank=True, default='', max_length=200, verbose_name='平台')),
                ('language', models.CharField(blank=True, default='', max_length=200, verbose_name='语言')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='发售日期')),
                ('score', models.DecimalField(blank=True, decimal_places=1, help_text='0-10 分', max_digits=4, null=True, verbose_name='玩家评分')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='评分人数')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('cover_url', models.URLField(blank=True, default='', max_length=500, verbose_name='封面图')),
                ('detail_url', models.URLField(blank=True, default='', max_length=500, verbose_name='来源链接')),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='抓取时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '单机游戏排行榜',
                'verbose_name_plural': '单机游戏排行榜',
                'db_table': 'single_player_rankings',
                'ordering': ['source', 'rank'],
            },
        ),
        migrations.AddField(
            model_name='singleplayerranking',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rankings', to='games.game', verbose_name='关联游戏'),
        ),
        migrations.AddIndex(
            model_name='singleplayerranking',
            index=models.Index(fields=['source', 'rank'], name='single_play_source_755d5e_idx'),
        ),
        migrations.AddIndex(
            model_name='singleplayerranking',
            index=models.Index(fields=['source', '-fetched_at'], name='single_play_source_2da3e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='singleplayerranking',
            unique_together={('source', 'rank')},
        ),
    ]
