# Generated by Django 4.2.16 on 2025-11-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_singleplayerranking_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gamescreenshot',
            new_name='game_screen_game_id_fdec5d_idx',
            old_name='game_screen_game_id_5e8f2c_idx',
        ),
    ]
