# Generated by Django 4.2.16 on 2025-11-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_rename_game_screen_game_id_5e8f2c_idx_game_screen_game_id_fdec5d_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='like_count',
            field=models.IntegerField(db_index=True, default=0, verbose_name='点赞数'),
        ),
    ]
